apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prestrafe-

configurations:
- kustomize-configurations/servicemonitor.yaml
- kustomize-configurations/sealedsecret.yaml

resources:
- imagepullsecret-sealed.yaml
- secret-sealed.yaml
- deployment.yaml
- service.yaml
- servicemonitor.yaml

commonLabels:
  app.kubernetes.io/component: bot
  app.kubernetes.io/managed-by: Kustomize
  app.kubernetes.io/name: prestrafe-bot
  app.kubernetes.io/part-of: prestrafe
  app.kubernetes.io/version: master

images:
- name: prestrafe-bot
  newName: registry.gitlab.com/prestrafe-twitchbot/prestrafe-bot
  newTag: 37aea5b9
