apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prestrafe-bot
  labels:
    release: monitoring
spec:
  endpoints:
    - honorLabels: true
      port: http-metrics
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: prestrafe-bot
