apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prestrafe-bot
spec:
  endpoints:
    - honorLabels: true
      targetPort: http-metrics
  selector:
    matchLabels:
      app: prestrafe-bot
