apiVersion: v1
kind: Service
metadata:
  name: prestrafe-bot
spec:
  ports:
    - name: http-metrics
      port: 9080
      targetPort: http-metrics
      protocol: TCP
  selector:
    app: prestrafe-bot
