apiVersion: v1
kind: Service
metadata:
  name: bot
  labels:
    app: prestrafe-bot
spec:
  ports:
    - name: svc-metrics
      port: 9080
      targetPort: http-metrics
      protocol: TCP
  selector:
    app: prestrafe-bot
